parameters:
    buzz.client.curl.class: Donato\Http\Proxied\BuzzBundle\Buzz\Client\CurlProxy

services:
    buzz.client.curl:
        class: %buzz.client.curl.class%
        public: true

    buzz.browser:
        class:     Buzz\Browser
        arguments: ['@buzz.client.curl']